const fs=require('node:fs');
const path=require('node:path');
const root=__dirname;
const output=path.join(root,'..','Noor_Kitchen_Coverage_Review.html');
const sources={v2:'C:/Users/Aly Jafferani/Desktop/Noor_Kitchen_Planner_v2.xlsx',final:'C:/Users/Aly Jafferani/Documents/Codex/2026-07-08/fianc-video-file-project/outputs/Noor_Kitchen_Planner_Final.xlsx',app:'C:/Users/Aly Jafferani/Documents/Codex/2026-07-08/fianc-video-file-project/outputs/Noor_Kitchen_App_v3.html'};
// Each row is one distinct capability, not a score or an assurance of full readiness.
const rows=[
['Excel','Household cooking count','Home!B5:E5; Lists!F2:F13','Partial','Present','HTML 111–112, 162; browser baseline','Make the number of people explicit for each planned meal and cooking event.'],
['Excel','Scale ingredient amounts to people served','Data!D3:G278; Recipe Card!C10:C27','Partial','Verified','HTML 125; browser navigation_and_mobile_layout','Preserve scaling and show the base servings beside the selected servings.'],
['Excel','Recheck availability when servings change','Data!J3:M278; What Can I Cook!M4:M25','Missing','Present','HTML 125–130','Recalculate suggestions, shortages, and shopping whenever servings change.'],
['Excel','Ready-to-cook dish count','Home!B8:F8','Missing','Verified','HTML 176–180; browser navigation_and_mobile_layout','Keep a Today summary of recipes for which all required amounts are available.'],
['Excel','Rank dishes by pantry ingredient coverage','What Can I Cook!D4:H25; Home!B13:F24','Missing','Present','HTML 126–130, 176–185','Keep suggestions alongside planning. Explain what the percentage means.'],
['Excel','Top ten recommendations on Home','Home!B13:F24','Missing','Partial','HTML 176 selects six non-ready recipes','Provide an expandable full ranked list. The current Tonight view limits near matches to six.'],
['Excel','List missing ingredients and quantities','Pantry!C4; Shopping List!E5; Data!M3:M278','Covered','Present','HTML 127–129, 194, 222–223','Show every shortage with quantity and unit, including the main ingredient of a dish.'],
['Excel','Search recipes by dish name','Recipes!A3:I3','Missing','Broken','HTML 213; browser ordinary_search_typing','Keep focus and the complete query while typing.'],
['Excel','Preserve the starter recipe collection','Recipes!A6:H27; Lists!A2:E23','Missing','Verified','Catalog reconciliation: 22 entries and 276 ingredient rows','Carry over all recipe IDs, ingredients, servings, times, notes, and links. Some dishes have variants.'],
['Excel','Recipe source servings','Recipes!C6:C27; Recipe Card!B4:C5','Partial','Present','HTML 193, 225','Show original servings and the selected cooking count.'],
['Excel','Prep and cooking time','Recipes!D6:D27; Recipe Card!B6:C6','Missing','Present','HTML 193, 225; catalog reconciliation','Preserve recipe time and add optional planning filters.'],
['Excel','Cooking tips and recipe notes','Recipes!H6:H27; Recipe Card!B7:C7','Missing','Present','HTML 226; catalog reconciliation','Keep recipe-specific notes and personal variations.'],
['Excel','Video recipe links','Recipes!E6:E27 hyperlinks; Lists!E2:E23','Missing','Present','HTML 196, 228; actual hyperlink targets reconciled','Keep video links. Their current availability and recipe accuracy were not checked.'],
['Excel','Written recipe links','Recipes!F6:F27 hyperlinks; Lists!D2:D23','Missing','Present','HTML 197, 229; actual hyperlink targets reconciled','Keep written sources beside the in-app recipe. External content was not verified.'],
['Excel','Recipe card with need, current stock, and status','Recipe Card!B9:F27','Partial','Partial','HTML 222–227 shows need and have/buy, without a numeric current-stock column','Show required amount, available amount, and shortfall together.'],
['Excel','Open a detailed card from a top recommendation','Home!D15:D24; Recipe Card!B2:F27','Missing','Partial','HTML Tonight cards have external links; internal cards are opened in Recipes','Let Today recommendations open the same detailed recipe card.'],
['Excel','Cooking history records the dish','Home!B26:E39','Partial','Verified','HTML 209; browser cooking_deduction_and_undo_log','Keep a full editable cooking history with stable meal-event IDs.'],
['Excel','Cooking date is user-selectable','Home!C28:C39; Lists!G2:G11','Missing','Partial','HTML 209 fixes date to now; browser local_date_month_boundary','Support today and backdated entries using the household timezone.'],
['Excel','Breakfast, lunch, dinner, and chai/snack','Home!D28:D39; Lists!H2:H5','Partial','Present','HTML 204','Retain all four choices and permit household-specific slot names.'],
['Excel','Record actual people served per cooking event','Home!E28:E39','Partial','Verified','HTML 201–209; browser cooking_deduction_and_undo_log','Store servings on the event independently of the household default.'],
['Excel','Deduct ingredients after cooking','Data!H3:I278; Pantry!H7:I68','Covered','Verified','HTML 131–132; browser cooking_deduction_and_undo_log','Preserve deduction, with a review of actual amounts used and a linked reversal.'],
['Excel','Pantry ingredient quantities and units','Pantry!A6:C68','Covered','Partial','HTML 243–250; browser manual_pantry_edit_persists','Add direct numeric entry and unit selection rather than relying on fixed increment buttons.'],
['Excel','Editable minimum-stock threshold','Pantry!D7:D68','Missing','Partial','HTML 133 reads thresholds from the database; no threshold editor','Let Noor set minimum and preferred restocking levels.'],
['Excel','Low-stock status and item count','Pantry!J7:J68; Home!B9:F9','Missing','Verified','HTML 133, 179, 243–244; browser baseline','Keep visible low-stock indicators and connect them to shopping.'],
['Excel','Ingredient usage totals from cooking history','Pantry!H7:H68; Data!I3:I278','Missing','Missing','HTML log stores dish, date, meal, and persons, without per-ingredient usage history','Keep ingredient movements so purchases, cooking, waste, and corrections can be traced.'],
['Excel','Calculated remaining pantry balance','Pantry!I7:I68','Covered','Verified','HTML 132, 250; browser pantry edit and cooking checks','Use a current balance backed by its movement history.'],
['Excel','Pantry last-updated date','Pantry!E7:E68','Missing','Missing','HTML state has no last-updated field per ingredient','Record when each stock quantity was last confirmed.'],
['Excel','Typed versus photo entry method','Pantry!F7:F68','Missing','Missing','HTML state does not store entry method per stock update','Preserve the source of each update.'],
['Excel','Photo notes for pantry entries','Pantry!G6:G68','Missing','Missing','HTML photo URL is transient; no persistent photo-note field','Keep useful notes and optional private image references on the update.'],
['Excel','External photo-to-Claude helper process','Pantry!A2; Home!B46','Replaced','Verified','HTML 251–287; browser photo_is_preview_and_manual_tiles','Retain manual fallback while adding integrated recognition. Current photo use is a visual aid.'],
['Excel','Ingredient presence checklist','What Can I Cook!A4:B65','Partial','Present','HTML Pantry quantities and recipe have/buy statuses','Distinguish some stock from enough stock for the selected recipe.'],
['Excel','Check whether a particular dish is possible','Pantry!C3:F4','Partial','Present','HTML 221–232','Use one consistent availability calculation in recipes, Today, and the planner.'],
['Excel','Shopping shortages for one selected dish','Shopping List!C5:E5','Partial','Present','HTML 295–301, 315–317','Keep single-dish shopping as an alternative to the weekly basket.'],
['Excel','Catalog-wide ingredient totals','Shopping List!C8:C69','Replaced','Missing','Excel C8 sums Data Qty(base) across the recipe catalog; HTML uses low stock and one dish','Replace shopping demand with the selected plan or basket. Catalog totals are not a weekly plan.'],
['Excel','Shopping organised by aisle','Shopping List!E8:E69','Missing','Verified','HTML 304–308; browser navigation_and_mobile_layout','Retain aisle grouping and household shopping categories.'],
['Excel','Shopping completion marks','Shopping List!A8:A69','Covered','Partial','HTML 311–314; browser threshold_shopping_uses_assumed_purchase','Capture actual quantities bought and keep completion marks consistent with undo.'],
['Excel','Store suggestions by shopping category','Shopping List!I8:I69; Home!B47','Missing','Present','HTML 103–106, 305','Make existing Islamabad suggestions editable. Current stores and delivery claims were not verified.'],
['Excel','Consistent ingredient identity across modules','Home!B49; Data!C3:C278','Partial','Present','HTML database IDs; full catalog reconciliation','Keep stable ingredient IDs and add user-friendly aliases.'],
['Legacy HTML','Recipe category filters','HTML 100–102, 214–216','Missing','Present','Recipe category buttons render in the browser','Keep category filters, personal recipes, and a reliable search.'],
['Legacy HTML','Create a personal recipe','HTML 356–391','Covered','Verified','browser custom_recipe_creation_backup_restore','Preserve creation and add full instructions, photos, and editing.'],
['Legacy HTML','Create a new ingredient','HTML 371–385','Covered','Partial','Creation is available within Add recipe, with fixed threshold 1','Make ingredient creation available directly from Pantry and photo review.'],
['Legacy HTML','Delete a personal recipe','HTML 392','Missing','Present','Source inspection; delete button appears for custom recipes','Confirm deletion and keep past cooking events intact.'],
['Legacy HTML','Undo a pantry change','HTML 122–123','Covered','Broken','Browser confirms stock-only reversal leaves cooking history and purchase marks unchanged','Reverse all linked effects of an event and keep a correction history.'],
['Legacy HTML','Local saving and reloading','HTML 113–121','Partial','Partial','Normal edit survives reload; simulated storage failure silently loses the edit','Show failed saves, preserve pending work, and provide reliable recovery.'],
['Legacy HTML','Export a backup','HTML 393','Missing','Verified','browser custom_recipe_creation_backup_restore','Keep an export containing pantry, recipes, plans, events, and settings.'],
['Legacy HTML','Restore a valid backup','HTML 394–397','Missing','Verified','Valid export restored a custom recipe and survived reload','Validate every imported field and preserve existing data before replacement. Malformed restore was not tested.'],
['Legacy HTML','Monthly cooking totals and dish rankings','HTML 328–345','Missing','Partial','Browser stats render; timezone boundary puts an October event in September','Retain summaries with local dates and clear servings rather than unique-person claims.'],
['Legacy HTML','Monthly breakdown by meal type','HTML 337, 343','Missing','Present','Browser cooking summary includes Dinner: 1','Keep breakfast, lunch, dinner, and snack history.'],
['Legacy HTML','Share shopping list and monthly summary','HTML 318–322, 347–350','Missing','Source only','Share functions exist; no external message was sent','Preserve user-initiated sharing. Delivery and mobile share-sheet behavior remain unverified.'],
['Legacy HTML','Personalised appearance and message','HTML 77–78, 173','Missing','Verified','390-pixel screenshot inspected','Preserve Noor-specific naming and the personal character of the app.'],
['Current requirements','Phone use and home-screen icon','User confirmed phone/home-screen use','Covered','Partial','Responsive HTML and Apple meta tag; no manifest or service worker in source','Deliver an installable app and verify installation on Noor’s actual phone.'],
['Current requirements','Integrated photo recognition','User requires pictures to update pantry','Covered','Missing','Browser photo upload creates 62 manual tiles; source has no image-analysis call','Photo to editable detected-item draft, then confirmation and save.'],
['Current requirements','Manual items with weights and amounts','User explicitly requested manual items, weight and quantities','Covered','Partial','Existing item edits work; new items are created through recipe flow','Allow direct item creation, exact quantity entry, and unit changes in Pantry.'],
['Proposed workflow','Weekly or multi-day meal planner','Prior workflow steps 4–5','Covered','Missing','No plan collection, planner view, or scheduled-meal state in HTML','Plan meals by date, slot, recipe, and servings, with swaps and cancellations.'],
['Proposed workflow','One shopping basket across planned meals','Prior workflow step 5','Covered','Missing','HTML supports thresholds and one dish; Excel totals the complete catalog','Aggregate selected future meals, subtract stock once, and include chosen restocking needs.'],
['Proposed workflow','New purchase versus remaining-stock correction','Prior workflow steps 2 and 6','Covered','Missing','HTML applyPaste overwrites amounts; no operation-purpose field','Use separate Add purchase and Set remaining amount actions.'],
['Proposed workflow','Review photo items before committing','Prior workflow steps 2 and 6','Covered','Partial','Photo tile buttons save immediately; pasted values have no parsed-item preview','Review additions, corrections, uncertainty, and before/after balances before save.'],
['Proposed workflow','Safe conversions between compatible units','Prior design: quantities, weights, and desi glossary','Partial','Broken','Browser paste converts Chicken 500 g to stored 500 kg by ignoring the input unit','Convert g/kg and ml/L; configure pao and dozen; require size for packets and ingredient-specific conversions for cups.'],
['Proposed workflow','Unknown versus measured quantity','Prior design: package labels and unknown amounts','Covered','Missing','HTML only stores a numeric quantity per ingredient','Separate package size, remaining amount, estimate, and unknown amount.'],
['Proposed workflow','Actual quantity bought and partial purchases','Prior workflow step 6','Covered','Missing','HTML purchase tick assumes a top-up to twice the minimum','Capture actual receipts and amounts, even when a purchase differs from the suggested quantity.'],
['Proposed workflow','Review actual ingredient usage after cooking','Prior workflow step 7','Covered','Missing','HTML cooking confirmation lets the user change servings and meal only','Accept recipe quantities or adjust each actual amount before deduction.'],
['Proposed workflow','Record everyday usage and finished items','Prior workflow step 7','Covered','Partial','Minus buttons change stock; no dedicated usage event or Finished action','Provide Used some, Finished, and Correction actions with undo.'],
['Proposed workflow','Edit recipes and retain full cooking steps','Prior workflow step 3','Partial','Missing','HTML custom recipe has name, ingredients, links and one notes field, without steps or edit flow','Add editable instructions and personal variations. Preserve the recipe version used in history.'],
['Thorough app proposal','Optional shared household access','Earlier proposal; user has not selected shared versus solo access','Conditional','Missing','HTML localStorage is device-local; no accounts or synchronization','If enabled, both members share plans, stock, recipes, and change history.'],
['Thorough app proposal','Leftovers as prepared food','Earlier Should feature','Deferred','Missing','No leftover or prepared-portion state','Record portions left, storage date, and their reuse as a later meal.'],
['Thorough app proposal','Fridge, freezer, and shelf locations','Earlier pantry proposal','Partial','Missing','No storage-location field','Track where items and separate packages or batches are stored.'],
['Thorough app proposal','Expiry and frozen-on dates','Earlier Should feature','Deferred','Missing','No expiry or frozen-on fields','Track optional supplied dates and use-soon indicators. Do not infer safe food from a photo.'],
['Thorough app proposal','Waste and spoilage records','New proposal arising from stock lifecycle review','Missing','Missing','No waste event type','Distinguish discarded food from cooking usage and stock corrections.'],
['Thorough app proposal','Editable local names and units','Earlier Roman Urdu/desi glossary proposal','Partial','Missing','Parser matches canonical English ingredient names and ignores unit text','Add reviewed aliases for ingredients and household unit conventions.'],
['Thorough app proposal','Family recipe import from photos','Earlier open decision/Delight feature','Deferred','Missing','No recipe image-extraction flow','Plan a separate review of ingredient amounts, instructions, and handwriting.'],
['Thorough app proposal','Guest meals and editable Ramadan slots','Earlier Should feature','Deferred','Partial','Servings and four meal types exist; no event plan or configurable slots','Use per-meal servings and editable occasion labels.'],
['Thorough app proposal','Actual grocery spending and budgeting','Earlier Should feature','Deferred','Missing','No purchase prices or spending history','Store actual purchase prices when entered and distinguish them from quantity estimates.'],
['Thorough app proposal','Prevent applying one purchase twice','Earlier photo/purchase design discussion','Partial','Missing','No purchase-batch IDs or receipt/photo reconciliation','Link review and stock changes to one accepted purchase event.'],
['Thorough app proposal','Backup validation and versioned recovery','Expanded reliability requirement','Missing','Partial','Valid backup tested; restore only checks for pantry property in source','Validate schema, migrate known versions, and keep a recoverable pre-import copy.'],
['Thorough app proposal','Offline reading and clear synchronization state','Earlier architecture proposal','Deferred','Partial','The local HTML runs without a backend; no shared synchronization or network-pending state exists','Make saved plans, recipes, and lists readable offline. Show pending changes clearly. Hosted photo analysis waits for internet.'],
['Thorough app proposal','Ingredient packages or batches with different dates','Expanded pantry lifecycle proposal','Missing','Missing','HTML stores one quantity for each ingredient','Keep separate packages or batches when expiry, frozen-on date, location, or quantity basis differs.'],
['Thorough app proposal','Editable complete cooking history','Expanded cooking-record requirement','Partial','Partial','HTML shows the last six meals on Tonight and monthly totals; no event editor or full-history screen','Browse, search, correct, backdate, and reverse cooking events without leaving inconsistent stock balances.']
];
const defects=[
['Search loses focus','Typing biryani leaves query b; typing chicken in Pantry leaves c.','HTML 213, 239','ordinary_search_typing','Keep the same input while updating results, or restore focus to the new input.'],
['Pasted quantity ignores its unit','Chicken - 500 g saves quantity 500 in the ingredient’s kg unit. Negative -2 is parsed as positive 2.','HTML 136–155, 284–286','paste_ignores_units_and_overwrites_stock','Parse and validate quantity and unit together. Reject invalid input and review the converted amount.'],
['Undo leaves the cooked meal counted','Chicken stock goes 1000 → 999.3333 → 1000, while cooking history still contains one meal and Stats still counts it.','HTML 122–123, 209','cooking_deduction_and_undo_log','Tie stock movements and history to the same event and reverse both.'],
['Purchase undo temporarily contradicts the checkbox','Undo returns Onion stock to 0 while the row remains checked and says in pantry. The purchase marker has a 2.6-second removal timer.','HTML 123, 311–314','threshold_shopping_uses_assumed_purchase','Reverse the purchase status with its stock update, without relying on a later timer.'],
['A local October meal is grouped into September','At 01:30 Karachi time on 1 October, the log displays 01 Oct but stores iso 2026-09-30 and Stats groups it under Sep 2026.','HTML 209, 326','local_date_month_boundary','Store the household local date separately from the timestamp used for ordering.'],
['Failed saving is hidden','With a simulated storage quota exception, Chicken changes 1 → 1.25 in memory, then reload returns 1 without an error message.','HTML 121','storage_failure_is_silent','Expose failed saves and retain a recoverable pending change. This is a simulated failure, not evidence of past user data loss.']
];
const workflow=[
['Set up the kitchen','Choose the usual number of people, meal names, preferred units, storage locations, and solo or shared access. Review starter stock instead of accepting sample quantities as real inventory.'],
['Bring in the recipe collection','Keep the existing 22 entries, ingredient quantities, times, notes, videos, and written links. Add and edit family recipes with full steps. Photo recipe import gets its own reviewed flow.'],
['Record actual pantry stock','Add items manually or review items detected from a picture. Enter quantity and unit, storage location, and optional expiry/frozen-on date. Keep uncertain amounts visible.'],
['Decide or plan','Today shows ready recipes and the best near matches. Noor can cook spontaneously or assign recipes and servings to dates and meal slots.'],
['Build the shopping basket','Combine the selected meals, subtract available stock once, and add chosen minimum-stock top-ups. Group by aisle and show dish-specific shortages and editable store hints.'],
['Record purchases','Tick what was bought, confirm the actual quantity and optional price, and update stock once. Link a receipt and grocery photo if they describe the same purchase.'],
['Cook and confirm usage','Open the scaled recipe, instructions, notes, or video. Record the actual cooking date, meal type, servings, and ingredient amounts used. Then update stock and history together.'],
['Handle the rest of kitchen life','Record chai ingredients and other everyday usage, remaining portions, food moved to the freezer, finished items, and waste. Corrections can be undone without corrupting history.'],
['Review and protect the records','See monthly meal and dish summaries, servings prepared, stock movements, and grocery spending where prices were captured. Share only on user action and support validated export and restore.']
];
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const htmlRows=rows.map((r,i)=>`<tr data-search="${escape(r.join(' ').toLowerCase())}" data-group="${escape(r[0])}" data-status="${escape(r[4])}"><td>${i+1}</td><td><b>${escape(r[1])}</b><small>${escape(r[0])}</small></td><td>${escape(r[2])}</td><td>${escape(r[3])}</td><td class="status ${r[4].toLowerCase().replace(/\s+/g,'-')}">${escape(r[4])}</td><td>${escape(r[5])}</td><td>${escape(r[6])}</td></tr>`).join('');
const books=JSON.parse(fs.readFileSync(path.join(root,'workbook-evidence.json'),'utf8'));
const tests=JSON.parse(fs.readFileSync(path.join(root,'browser-evidence.json'),'utf8'));
const reconciliation=JSON.parse(fs.readFileSync(path.join(root,'reconciliation.json'),'utf8'));
const coverage={date:'2026-10-04',sources,definitions:{workflow:'The seven-step plain-English workflow given immediately before the new files were supplied.',excel:'Capabilities found in both workbooks. Workbook instructions are evidence of source intent, not new user instructions.',app:'The supplied earlier HTML v3, not a newly built phone app.',verified:'Observed in an isolated desktop Chrome browser or fully reconciled as catalog data. This is not physical-phone acceptance.',present:'Present in source; complete user behavior has not been independently verified.',partial:'Some behavior exists but is incomplete for the described need.',broken:'A defect was reproduced in isolated browser checks.',missing:'No implementing view/state/function found in the supplied source.'},requirements:[{requirement:'Inspect all supplied sources',status:'Proven',evidence:'Both workbooks: eight sheets each including hidden Lists; complete HTML source and embedded catalog.'},{requirement:'Check Excel ideas against workflow and app separately',status:'Proven',evidence:`${rows.length} capability rows with source references and separate workflow/app statuses.`},{requirement:'Preserve confirmed photo/manual pantry and phone requirements',status:'Proven',evidence:'Dedicated Current requirements rows and expanded workflow.'},{requirement:'Design for a thorough app',status:'Partial',evidence:'Fuller feature baseline and reliability corrections proposed. App implementation and final product choices remain outstanding.'}],rows:rows.map((r,i)=>({id:i+1,group:r[0],feature:r[1],source:r[2],priorWorkflow:r[3],legacyApp:r[4],evidence:r[5],futureAction:r[6]})),defects,workflow,verification:{browserChecks:tests.length,verificationErrors:tests.filter(x=>x.status==='verification_error').length,width:390,timezone:'Asia/Karachi',sourceHashes:books.map(x=>({file:x.file,sha256:x.sha256})),catalogReconciliation:reconciliation},limitations:['No native Excel recalculation was performed. Formula text, cached values, raw XML dropdowns, hidden content, and relationships were inspected.','Browser checks used disposable isolated data and local files. No real household data or original source file was changed.','Physical Android/iPhone camera capture, home-screen installation, offline synchronization, cloud vision, multi-user access, and external sharing delivery were not tested.','Recipe/video URLs and store suggestions were preserved but their current availability, accuracy, ranking, prices, and delivery claims were not verified.','A valid backup/restore was tested; malformed restore payloads were not tested.']};
fs.writeFileSync(path.join(root,'coverage-matrix.json'),JSON.stringify(coverage,null,2));
const report=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Noor’s Kitchen — coverage review</title><style>
:root{color-scheme:light dark;--bg:#fffafc;--fg:#302330;--muted:#675a67;--line:#e4d7df;--accent:#9c245a;--panel:#f7eef3}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--fg);font:16px/1.6 system-ui,Arial,sans-serif}main{max-width:1500px;margin:auto;padding:28px clamp(16px,4vw,48px) 60px}h1{font-size:clamp(28px,4vw,42px);line-height:1.15}h2{margin-top:38px;font-size:24px}h3{font-size:18px}p{max-width:100ch}small{display:block;color:var(--muted);font-size:12px;margin-top:4px}a{color:var(--accent)}header{border-bottom:1px solid var(--line);padding-bottom:22px}.lead{font-size:20px;max-width:90ch}.metadata{color:var(--muted)}nav{display:flex;flex-wrap:wrap;gap:16px;margin-top:18px}section{margin-top:26px}li{margin:10px 0}.controls{display:flex;flex-wrap:wrap;gap:12px;align-items:end;margin:16px 0}.controls label{display:flex;flex-direction:column;gap:6px}input,select,button{font:inherit;min-height:44px;border:1px solid var(--line);border-radius:6px;background:var(--bg);color:var(--fg);padding:8px 12px}input{width:min(400px,80vw)}.table-wrap{overflow-x:auto}table{border-collapse:collapse;width:100%;min-width:1050px;font-size:14px}th,td{padding:12px;text-align:left;vertical-align:top;border-bottom:1px solid var(--line)}th{background:var(--panel)}td:nth-child(2){min-width:190px}td:nth-child(3){min-width:145px}td:nth-child(6){min-width:195px}td:nth-child(7){min-width:240px}.status{font-weight:700}.broken,.missing{color:#a82035}.partial{color:#875313}.verified{color:#246c41}.defect{border-top:1px solid var(--line);padding:12px 0}.definition{color:var(--muted)}.workflow{max-width:100ch}.sources{overflow-wrap:anywhere}.note{background:var(--panel);padding:16px;border-left:4px solid var(--accent)}[hidden]{display:none!important}@media(prefers-color-scheme:dark){:root{--bg:#21191e;--fg:#f2eaf0;--muted:#c4b3bf;--line:#54434e;--accent:#f6a9cd;--panel:#34252f}.broken,.missing{color:#ffb3bb}.partial{color:#f4ce96}.verified{color:#a7dfb9}}@media print{nav,.controls{display:none}main{padding:0}table{min-width:0;font-size:9px}th,td{padding:5px}td{min-width:0!important}body{background:white;color:black}}
</style></head><body><main><header><p class="metadata">Review date: 4 October 2026 · Source files inspected without modification</p><h1>Noor’s Kitchen coverage review</h1><p class="lead"><b>The earlier workflow did not capture every idea in the Excel planners. The HTML preserves the recipe catalog and several useful kitchen functions, but it has feature gaps and reproduced defects.</b></p><p>The fuller app should combine meal planning, pantry-based suggestions, recipe cards, shopping, actual cooking records, stock history, and recovery. The original one-week pilot is not a cap on the intended product.</p><nav><a href="#summary">Findings</a><a href="#workflow">Expanded workflow</a><a href="#matrix">Feature comparison</a><a href="#defects">Verified defects</a><a href="#checks">Verification</a></nav></header>
<section id="summary"><h2>What the sources establish</h2><ul><li>Both Excel planners have the same eight sheets, including a hidden Lists sheet. After normalizing array-formula range notation, their cell differences are the default person count, one selected recipe, and footer punctuation. Their dropdown storage differs, but the intended eleven validation rules are present in both.</li><li>All 22 recipe entries, 62 ingredients, and 276 recipe-ingredient rows reconcile to the HTML. Names, servings, times, notes, recipe and video hyperlink targets, ingredient units, initial stock, and minimum thresholds also reconcile.</li><li>The brief workflow omitted ranked suggestions, source links, recipe times and notes, minimum-stock controls, ingredient update metadata, cooking-date choices, store grouping, monthly history, and backup/recovery detail.</li><li>The HTML does not contain a weekly meal plan or a shopping basket derived from several planned meals. Its shopping uses low-stock thresholds and one selected dish.</li><li>The current photo feature displays a photo for manual edits and supports an external Claude copy/paste helper. It does not analyse the image inside the app.</li></ul><p class="note"><b>Shopping needs a deliberate redesign.</b> The Excel catalog-total column sums ingredients across all recipes. It is not the amount needed for a selected week. Preserve single-dish shortages, minimum stock, and aisle grouping; calculate the new basket from the actual selected meals and servings.</p><p>Confirmed requirements: phone with home-screen access, photo pantry updates, and manual items with quantities and weights. Shared access, recipe-photo import, budget features, and the remaining proposals have not all been approved as v1 commitments.</p></section>
<section id="workflow"><h2>Expanded plain-English workflow</h2><ol class="workflow">${workflow.map(x=>`<li><b>${escape(x[0])}.</b> ${escape(x[1])}</li>`).join('')}</ol></section>
<section id="matrix"><h2>Feature comparison</h2><p>The workflow column assesses the seven-step explanation given before these earlier files were supplied. <b>Covered</b> means explicit; <b>Partial</b> means only part was described; <b>Missing</b> means it was omitted. Deferred features were discussed earlier but omitted from that short operational explanation. Replaced identifies a source mechanism whose intent is served differently in the proposal.</p><p class="definition">For the HTML: <b>Verified</b> means observed in isolated checks or fully reconciled as catalog data. <b>Present</b> means source code exists. <b>Partial</b>, <b>Broken</b>, and <b>Missing</b> identify limitations. <b>Source only</b> means the external action was not exercised.</p><div class="controls"><label>Find a feature<input id="search" type="search" placeholder="Photo, shopping, recipe, undo…"></label><label>Feature source<select id="group"><option value="">All sources</option>${[...new Set(rows.map(r=>r[0]))].map(x=>`<option>${escape(x)}</option>`).join('')}</select></label><label>Earlier HTML status<select id="status"><option value="">All statuses</option>${[...new Set(rows.map(r=>r[4]))].sort().map(x=>`<option>${escape(x)}</option>`).join('')}</select></label><button id="reset" type="button">Reset filters</button><span id="count" aria-live="polite">${rows.length} features</span></div><div class="table-wrap"><table><thead><tr><th>ID</th><th>Capability</th><th>Source location</th><th>Prior workflow</th><th>Earlier HTML</th><th>Evidence</th><th>Fuller-app action</th></tr></thead><tbody>${htmlRows}</tbody></table></div></section>
<section id="defects"><h2>Defects reproduced in isolated browser checks</h2>${defects.map(x=>`<article class="defect"><h3>${escape(x[0])}</h3><p>${escape(x[1])}</p><p><b>Correction:</b> ${escape(x[4])}</p><small>${escape(x[2])} · Check: ${escape(x[3])}</small></article>`).join('')}</section>
<section id="checks"><h2>Verification and limits</h2><p>Inspected all sixteen worksheets, including hidden sheets, formulas, cached values, hyperlinks, comments, dropdown XML, and all HTML source. Compared source catalog contents and ran ${tests.length} focused browser checks in headless Chrome at 390 × 844 pixels, with Asia/Karachi timezone and disposable data. No browser verification errors were recorded. This does not mean that the reproduced product defects passed.</p><ul>${coverage.limitations.map(x=>`<li>${escape(x)}</li>`).join('')}</ul><h3>Source files</h3><ul class="sources">${Object.entries(sources).map(([key,value])=>`<li>${escape(key==='v2'?'Excel v2':key==='final'?'Excel Final':'Earlier HTML v3')}: ${escape(value)}</li>`).join('')}</ul><p><b>Decision:</b> Use the existing catalog and functional ideas as the baseline for a full specification. The earlier HTML needs repairs and the missing workflows before it meets the intended phone-app scope. No source app or workbook was modified by this review.</p></section></main><script>const search=document.getElementById('search'),group=document.getElementById('group'),status=document.getElementById('status'),count=document.getElementById('count');const records=[...document.querySelectorAll('tbody tr')];function filter(){let n=0;const q=search.value.trim().toLowerCase();for(const row of records){const show=(!q||row.dataset.search.includes(q))&&(!group.value||row.dataset.group===group.value)&&(!status.value||row.dataset.status===status.value);row.hidden=!show;if(show)n++;}count.textContent=n+' of '+records.length+' features';}search.addEventListener('input',filter);group.addEventListener('change',filter);status.addEventListener('change',filter);document.getElementById('reset').addEventListener('click',()=>{search.value='';group.value='';status.value='';filter();});</script></body></html>`;
fs.writeFileSync(output,report);
console.log(JSON.stringify({output,features:rows.length,defects: defects.length,browserChecks:tests.length,verificationErrors:coverage.verification.verificationErrors,groups:rows.reduce((a,r)=>(a[r[0]]=(a[r[0]]||0)+1,a),{})}));
