const fs=require('node:fs');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const {chromium}=require('C:/Users/Aly Jafferani/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--disable-gpu']});
 const page=await browser.newPage({viewport:{width:1366,height:900}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(pathToFileURL(path.join(__dirname,'..','Noor_Kitchen_Coverage_Review.html')).href,{waitUntil:'domcontentloaded'});
 const before=await page.locator('tbody tr:visible').count();
 await page.locator('#search').fill('photo');
 const filtered=await page.locator('tbody tr:visible').count();
 await page.locator('#reset').click();
 await page.locator('#group').selectOption('Excel');
 const excel=await page.locator('tbody tr:visible').count();
 await page.locator('#reset').click();
 await page.locator('#status').selectOption('Broken');
 const broken=await page.locator('tbody tr:visible').count();
 await page.locator('#reset').click();
 const restored=await page.locator('tbody tr:visible').count();
 await page.screenshot({path:path.join(__dirname,'coverage-report-desktop.png')});
 await page.setViewportSize({width:390,height:844});
 const mobile=await page.evaluate(()=>({documentWidth:document.documentElement.scrollWidth,viewport:innerWidth}));
 const matrix=JSON.parse(fs.readFileSync(path.join(__dirname,'coverage-matrix.json'),'utf8'));
 const result={expected:matrix.rows.length,before,filtered,excel,broken,restored,mobile,pageErrors:errors};
 fs.writeFileSync(path.join(__dirname,'report-verification.json'),JSON.stringify(result,null,2));
 await browser.close();
 if(before!==matrix.rows.length||restored!==before||excel!==38||filtered===0||filtered>=before||errors.length||mobile.documentWidth>mobile.viewport)throw new Error(JSON.stringify(result));
 console.log(JSON.stringify(result));
})().catch(e=>{console.error(e);process.exitCode=1});
