// Regenerates docs/FEATURES.md from audit/coverage-matrix.json.
// The phase of each matrix row is assigned here, in PHASE_OF, and nowhere else.
// Run: node tools/build_feature_catalog.cjs
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const matrix = JSON.parse(fs.readFileSync(path.join(root, 'audit', 'coverage-matrix.json'), 'utf8'));

const PHASES = {
  P0: 'Foundations: data model, units, seed import, safe saving',
  P1: 'Cook from what we have (v3 parity, without the defects)',
  P2: 'Plan the week and shop',
  P3: 'Photo pantry and receipts',
  P4: 'Kitchen depth: locations, batches, expiry, leftovers, waste',
  P5: 'Household, history and insights',
};

const PHASE_OF = {
  P0: [9, 38, 44, 58, 59, 69, 74],
  P1: [1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       31, 32, 39, 40, 41, 42, 43, 45, 46, 47, 48, 50, 51, 53, 56, 61, 62, 63, 77],
  P2: [33, 34, 35, 36, 37, 49, 54, 55, 60, 71, 72],
  P3: [28, 29, 30, 52, 57, 73],
  P4: [65, 66, 67, 68, 76],
  P5: [64, 70, 75],
};

const phaseById = new Map();
for (const [phase, ids] of Object.entries(PHASE_OF)) {
  for (const id of ids) {
    if (phaseById.has(id)) throw new Error(`Row ${id} is assigned to two phases`);
    phaseById.set(id, phase);
  }
}
const missing = matrix.rows.filter(r => !phaseById.has(r.id)).map(r => r.id);
if (missing.length) throw new Error(`Rows without a phase: ${missing.join(', ')}`);

const cell = s => String(s ?? '').replace(/\|/g, '\\|').replace(/\s+/g, ' ').trim();
const out = [
  '# Feature catalogue',
  '',
  '<!-- Generated by tools/build_feature_catalog.cjs from audit/coverage-matrix.json. Do not edit by hand; change PHASE_OF in the script and re-run it. -->',
  '',
  `All ${matrix.rows.length} capabilities from Codex's coverage review (2026-10-04), grouped by delivery phase.`,
  'Row numbers are the matrix IDs, so tickets, commits and the review can refer to them as `F<n>` (for example `F43`).',
  '',
  'Status columns come from the review: **Prior** is the earlier short workflow, **v3** is `sources/Noor_Kitchen_App_v3.html`',
  '(Present = in the source, Verified = observed working in a browser, Partial, Broken, Missing, Source only).',
  '',
];
for (const [phase, title] of Object.entries(PHASES)) {
  const rows = matrix.rows.filter(r => phaseById.get(r.id) === phase);
  out.push(`## ${phase}: ${title} (${rows.length})`, '', '| ID | Feature | Origin | Prior | v3 | What to build |', '|---|---|---|---|---|---|');
  for (const r of rows) {
    out.push(`| F${r.id} | ${cell(r.feature)} | ${cell(r.group)} | ${cell(r.priorWorkflow)} | ${cell(r.legacyApp)} | ${cell(r.futureAction)} |`);
  }
  out.push('');
}
fs.writeFileSync(path.join(root, 'docs', 'FEATURES.md'), out.join('\n'));
console.log(`Wrote docs/FEATURES.md with ${matrix.rows.length} rows`);
