// Regenerates docs/RECIPE_SOURCES.md from docs/research/recipe-research-2026-10-04.json.
// The JSON is the research record (links, ratings, view counts and feedback summaries,
// read on 2026-10-04). Run: node tools/build_recipe_sources.cjs
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const research = JSON.parse(fs.readFileSync(path.join(root, 'docs', 'research', 'recipe-research-2026-10-04.json'), 'utf8'));
const dishes = research.dishes;

const cell = s => String(s ?? '').replace(/\|/g, '\\|').replace(/\s+/g, ' ').trim();
const norm = u => String(u || '').toLowerCase().replace(/^https?:\/\/(www\.)?/, '').replace(/\/$/, '');
const site = u => norm(u).split('/')[0];
const find = (list, url) => (list || []).find(x => norm(x.url) === norm(url));

const rows = dishes.map(d => {
  const rec = d.recommended || {};
  const cur = d.current || {};
  const w = find(d.written, rec.written_url);
  const v = find(d.videos, rec.video_url);
  const writtenSame = norm(rec.written_url) === norm(cur.written_url);
  const videoSame = norm(rec.video_url) === norm(cur.video_url);
  const change = writtenSame && videoSame ? 'Keep both' : writtenSame ? 'New video' : videoSame ? 'New recipe' : 'New both';
  const num = x => (String(x ?? '').match(/\d[\d,.]*/) || [''])[0];
  const stars = w ? num(w.rating) : '';
  const rating = stars ? `${stars} from ${num(w.rating_count) || '?'}` : 'no rating shown';
  const views = num(v ? v.views : cur.video_views) || 'not verified';
  return { d, rec, change, rating, views };
});

const out = [
  '# Recipe and video sources for the 22 starter dishes',
  '',
  '<!-- Generated by tools/build_recipe_sources.cjs from docs/research/recipe-research-2026-10-04.json. Do not edit by hand. -->',
  '',
  'Researched on 2026-10-04 for F78. Each dish was ranked by recipe-page star ratings, YouTube views,',
  'and what Reddit users and YouTube commenters say. Numbers are as read on that date; anything that',
  'could not be checked is marked "not verified" in the JSON. Links point to the original sources;',
  'no recipe text is copied. These are recommendations for Aly and Noor to accept, not yet the app\'s data.',
  '',
  `Summary: ${rows.filter(r => r.change === 'Keep both').length} keep both current links, ` +
    `${rows.filter(r => r.change !== 'Keep both').length} have a better-received recipe or video.`,
  '',
  '| ID | Dish | Change | Recommended recipe | Rating | Recommended video | Views | Why |',
  '|---|---|---|---|---|---|---|---|',
];
for (const { d, rec, change, rating, views } of rows) {
  out.push(`| ${d.id} | ${cell(d.dish)} | ${change} | [${site(rec.written_url)}](${rec.written_url}) | ${cell(rating)} | [video](${rec.video_url}) | ${cell(views)} | ${cell(rec.reason)} |`);
}
out.push('', '## Cooking tips from Reddit and YouTube comments', '');
for (const d of dishes) {
  const tips = [...(d.reddit || []).map(r => r.summary), ...(d.videos || []).slice(0, 1).map(v => v.comment_feedback)]
    .filter(Boolean).map(cell);
  if (!tips.length) continue;
  out.push(`**${d.id} ${cell(d.dish)}**`, '');
  for (const t of tips.slice(0, 3)) out.push(`- ${t}`);
  out.push('');
}
out.push('## Limits', '');
for (const m of research.method || []) out.push(`- ${cell(m)}`);
out.push('');
fs.writeFileSync(path.join(root, 'docs', 'RECIPE_SOURCES.md'), out.join('\n'));
console.log(`Wrote docs/RECIPE_SOURCES.md with ${rows.length} dishes`);
